defmodule Exmarket.Crypto do
  defstruct symbol: "BTCUSDT",
            companyName: "Bitcoin USD",
            primaryExchange: "crypto",
            sector: "cryptocurrency",
            open: nil,
            openTime: nil,
            close: nil,
            closeTime: nil
end

# {
#   "symbol":"BTCUSDT",
#   "companyName":"Bitcoin USD",
#   "primaryExchange":"crypto",
#   "sector":"cryptocurrency",
#   "calculationPrice":"realtime",
#   "open":3527.79,
#   "openTime":1548082840296,
#   "close":3522.05522498,
#   "closeTime":1548169240296,
#   "high":3590.51,
#   "low":3434.85,
#   "latestPrice":3563.22,
#   "latestSource":"Real time price",
#   "latestTime":"10:00:40 AM",
#   "latestUpdate":1548169240296,
#   "latestVolume":28053.196533,
#   "iexRealtimePrice":null,
#   "iexRealtimeSize":null,
#   "iexLastUpdated":null,
#   "delayedPrice":null,
#   "delayedPriceTime":null,
#   "extendedPrice":null,
#   "extendedChange":null,
#   "extendedChangePercent":null,
#   "extendedPriceTime":null,
#   "previousClose":3527.79,
#   "change":35.43,"changePercent":0.01004,
#   "iexMarketPercent":null,
#   "iexVolume":null,
#   "avgTotalVolume":null,
#   "iexBidPrice":null,
#   "iexBidSize":null,
#   "iexAskPrice":null,
#   "iexAskSize":null,
#   "marketCap":null,
#   "peRatio":null,
#   "week52High":null,
#   "week52Low":null,
#   "ytdChange":null,
#   "bidPrice":3562.94,
#   "bidSize":0.061728,
#   "askPrice":3563.22,
#   "askSize":0.134326
# }
